### ISSUE TITLE
setting CHEAT_EDITOR, VISUAL, or EDITOR does not work

### ISSUE THREAD

**Issue by seansco** [cheat/cheat#412]
env output:
EDITOR=vi
CHEAT_EDITOR=vi
VISUAL=vi

cheat -e test still uses nano

<system>:~$ cheat -v
cheat 2.3.1

<system>:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

installed via "sudo snap install cheat"

**Comment by bernermic** [comment]
@seansco this is due to the fact that vi is not visible within the snap context right now. 
I created the snap version of cheat and I tried to get vim working there. That was up until now not working.
I‘ll try to figure out how to get it working.
If someone knows how that is please get in touch with me.

**Comment by chrisallenlane** [comment]
@bernermic, please see #414. I'm wondering if packaging the app in "classic" confinement is part of the solution here.

**Comment by seansco** [comment]
I installed from git and it works.  If you install from snap cheat could not see any of the ENV vars

**Comment by chrisallenlane** [comment]
Thanks for the info, @seansco. And I'm glad to hear that you got it working.

@bernermic, I've been screwing around with the `snapfile.yaml` for a few hours over here. Here are some findings:

- If you build and install the snap in `--classic` mode, while specifying `strict` confinement in `snapfile.yaml`, the `cheat` executable is able to read and respond to the relevant ennvars.
- If you build and install the snap in `--classic` mode and **also** specify `classic` confinement in `snapfile.yaml`, the snap installs, but the `cheat` executable fails with an error message resembling the following:

```
Can not open /var/lib/snapd/seccomp/profiles//snap.cheat.cheat (No such file or directory)
aborting: No such file or directory
```

I have no explanation for this :frowning_face: 

I'll also note that there is unfortunately **nothing** I can do that seems to allow the `cheat` executable to spawn a new process. (I was optimistic about the `process-control` interface, but it didn't work.)

For reference, this is the approximate state of my local `snapcraft.yaml` file:

```yaml
name: cheat
version: 'v2.3.1.build.4'
summary: cheat allows to create and view interactive cheatsheets on the command-line.
description: |
  cheat allows you to create and view interactive cheatsheets on the command-line. 
  It was designed to help remind *nix system administrators of options for commands 
  that they use frequently, but not frequently enough to remember.
  Source comes from https://github.com/chrisallenlane

grade: stable         # must be 'stable' to release into candidate/stable channels
confinement: strict  # use 'strict' once you have the right plugs and slots

apps:
  cheat:
    command: cheat
    plugs:
    #- process-control #nope
    - classic-support
    - cups-control
    - desktop
    - desktop-legacy
    - gsettings
    - unity7
    - wayland
    #slots:
    #- cheat-svc

#slots:
  #cheat-svc:
    #interface: dbus
    #bus: session
    #name: org.gnome.foo
    
parts:
  cheat:
    source: https://github.com/chrisallenlane/cheat.git
    plugin: python
    python-version: python3
    python-packages:
      - termcolor
      - docopt
      - pygments
    #override-build: |
      #git apply $SNAPCRAFT_STAGE/../patches/Bugfix-encoding-issue.patch
      #snapcraftctl build
```

I really don't know where to go from here. I've tried every `plug` that I thought could possibly be relevant.
