### ISSUE TITLE
failed to load config: config error: cheatpath path is not unique

### ISSUE THREAD

**Issue by roachsinai** [cheat/cheat#572]
Below is output of `cheat -d`:

```
community: /usr/share/cheat/cheatsheets/community
personal:  /home/roach/Nutstore Files/我的坚果云/.cheat
```

**A description of the problem**

If I'm under directory `/home/roach/Nutstore Files/我的坚果云`, any `cheat` command will got an error saying: `failed to load config: config error: cheatpath path is not unique: /home/roach/Nutstore Files/我的坚果云/.cheat`

But if under `/usr/share/cheat/cheatsheets/` no error.

Not know the reason is `space` in personal path, or Chinese character in personal path.

**cheat version info**: `4.0.1`

**cheat configuration info**

The contents of your `conf.yml` file

```
editor: vim

colorize: true

style: github

formatter: terminal256

cheatpaths:

  - name: community
    path: /usr/share/cheat/cheatsheets/community
    tags: [ community ]
    readonly: true

  - name: personal
    path: /home/roach/Nutstore Files/我的坚果云/.cheat
    tags: [ personal ]
    readonly: false
```
