### ISSUE TITLE
Incomplete conf.yml description

### ISSUE THREAD

**Issue by EmilySeville7cfg** [cheat/cheat#656]
**A description of the problem**

There is no info about:

- default values of props
- required props

```yml
# conf.yml:
# ...
cheatpaths:
  - name: community                   # a name for the cheatpath
    path: ~/documents/cheat/community # the path's location on the filesystem
    tags: [ community ]               # these tags will be applied to all sheets on the path
    readonly: true                    # if true, `cheat` will not create new cheatsheets here

  - name: personal
    path: ~/documents/cheat/personal  # this is a separate directory and repository than above
    tags: [ personal ]
    readonly: false                   # new sheets may be written here
# ...
```

I assume that:

- required props are: `name`, `path`
- `readonly` default is false

Am I right?
