### ISSUE TITLE
Version 4.2.7 broke personal cheatsheets in custom location

### ISSUE THREAD

**Issue by mikemcduffie** [cheat/cheat#690]
Thanks for submitting a bug report. Please provide the following information:

**A description of the problem**
I store my personal cheatsheets in a synced folder (/Users/mike/Resilio Sync/App Support/cheat/cheatsheets/personal) as configured in conf.yml. This has worked fine until version 4.2.7. Since upgrading my configuration no longer works:
- cheat -l                       : no output
- cheat -s \<term\>         : no output
- cheat \<cheatsheet\>   :  No cheatsheet found for \<cheatsheet\>. 

Downgrading to 4.2.6 resolved the issue for me with no other changes to my configuration.

**cheat version info**
4.2.7

**cheat configuration info**

If your bug pertains to how cheatsheets are loaded and/or displayed, please
paste here the following information:

1. The output of `cheat -d`
community: /Users/mike/.config/cheat/cheatsheets/community
personal:  /Users/mike/Resilio Sync/App Support/cheat/cheatsheets/personal
3. The contents of your `conf.yml` file

```yml
# The editor to use with 'cheat -e <sheet>'. Defaults to $EDITOR or $VISUAL.
editor: bbedit
# Should 'cheat' always colorize output?
colorize: false

# Which 'chroma' colorscheme should be applied to the output?
# Options are available here:
#   https://github.com/alecthomas/chroma/tree/master/styles
# style: monokai

# Which 'chroma' "formatter" should be applied?
# One of: "terminal", "terminal256", "terminal16m"
formatter: terminal

# Through which pager should output be piped? (Unset this key for no pager.)
pager: bat -l bash --style=plain
# pager: less -FRX # <- recommended where available

# The paths at which cheatsheets are available. Tags associated with a cheatpath
# are automatically attached to all cheatsheets residing on that path.
#`
# Whenever cheatsheets share the same title (like 'tar'), the most local
# cheatsheets (those which come later in this file) take precedent over the
# less local sheets. This allows you to create your own "overides" for
# "upstream" cheatsheets.
#`
# But what if you want to view the "upstream" cheatsheets instead of your own?
# Cheatsheets may be filtered via 'cheat -t <tag>' in combination with other
# commands. So, if you want to view the 'tar' cheatsheet that is tagged as
# 'community' rather than your own, you can use: cheat tar -t community
cheatpaths:

# Paths that come earlier are considered to be the most "global", and will
# thus be overridden by more local cheatsheets. That being the case, you
# should probably list community cheatsheets first.
#
# Note that the paths and tags listed below are placeholders. You may freely
# change them to suit your needs.
#
# Community cheatsheets must be installed separately, though you may have
# downloaded them automatically when installing 'cheat'. If not, you may
# download them here:
#`
# https://github.com/cheat/cheatsheets
#`
# Once downloaded, ensure that 'path' below points to the location at which
# you downloaded the community cheatsheets.
- name: community
  path: /Users/mike/.config/cheat/cheatsheets/community
  tags: [ community ]
  readonly: true

# If you have personalized cheatsheets, list them last. They will take
# precedence over the more global cheatsheets.
- name: personal
  path: /Users/mike/Resilio Sync/App Support/cheat/cheatsheets/personal
  tags: [ personal ]
  readonly: false

# While it requires no configuration here, it's also worth noting that
# 'cheat' will automatically append directories named '.cheat' within the
# current working directory to the 'cheatpath'. This can be very useful if
# you'd like to closely associate cheatsheets with, for example, a directory
# containing source code.
#
# Such "directory-scoped" cheatsheets will be treated as the most "local"
# cheatsheets, and will override less "local" cheatsheets. Likewise,
# directory-scoped cheatsheets will always be editable ('readonly: false').
```
